name: clang-format

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  clang-format:
    name: clang-format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Run clang-format check script
        run: |
          echo "=== clang-format check start ==="
          ./run-clang-format.py --style file -r object_tracking
          ./run-clang-format.py --style file -r object_detection
          ./run-clang-format.py --style file -r result_showing
          echo "=== clang-format check finished ==="
